Repository growthbook/growthbook, pull requests merged in 2023-12, with the labels that each got.

#1900 Update README.md for docs site
  docs/README.md
Labels: documentation

#1948 Replace Papercups with Pylon
  packages/front-end/components/Auth/InAppHelp.tsx
Labels: enhancement

#1895 Fix expired license error handling
  packages/back-end/src/services/auth/verifyLicenseMiddleware.ts
  packages/enterprise/src/license.ts
  packages/enterprise/test/license.test.ts
Labels: bug
